global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:300']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 5s

  - job_name: 'nats-exporter'
    static_configs:
      - targets: ['nats-exporter:7777']
    scrape_interval: 5s

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093